function afficheEditeur(){
document.write('<div><form><p> id question : sera généré automatiquement</p>'
+'<p>parcour : <textarea></textarea></p>'
+'<p>salle : <textarea>au format [étage]_r[numSalle]</textarea></p>'
+'<p>enoncer : <textarea></textarea></p>'
+'<p>bonne reponse :' 
+'<select>'
+'<option value="1">reponse 1</option>'
+'<option value="2">reponse 2</option>'
+'<option value="3">reponse 3</option>'
+'<option value="4">reponse 4</option>'
+'</select></p>'
+'<p>reponse 1 : <textarea></textarea></p>'
+'<p>reponse 2 : <textarea></textarea></p>'
+'<p>reponse 3 : <textarea></textarea></p>'
+'<p>reponse 4 : <textarea></textarea></p>'
+'<p><input type="submit" value="Envoyer" ></p></form></div>');}
